### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by EthanYT** [Shadersoft/UniverseMG#10]
/admin
Makes a player(admin) invisible COMPLETLY, so the other person can't see what's in the admins hand. It also puts a spawn egg in there hand.

**Comment by SorryIm2Fresh** [comment]
I'll do this in my next update.

**Comment by DUFCLiam** [comment]
Why does it need to add a spawn egg? Also add this as a /vanish command; Hides you from tab and fakes a leave if you use it with a `-l` suffix.

**Comment by EthanYT** [comment]
because it will test people for kill aura @DUFCLiam

**Comment by DUFCLiam** [comment]
@EthanYT They can have mobs disabled in there aura...

**Comment by Mafrans** [comment]
@EthanYT @DUFCLiam Kill aura will affect players in vanish as well, so there is no need for checking it.

ONT: adding this in my next commit
